src/components/form/HdGoogleAutocomplete.vue
If the component is unmounted before it has the time to fetch the Google API, the ref will not be defined and so an error is thrown.
This change makes sure we check for the existence of the ref before proceeding.
=> [B] Check if ref is defined before proceeding with initializing

src/services/scrolling.js, src/services/utils.js
Sometimes we want to have a custom offset instead of `window.innerHeight` in `isScrolledPastElBottom`.
And on the way, I deleted the obsolete `loadJSAsync` function, we should use `loadScript` instead :)
=> [T] Update the services

src/components/gallery/HdGalleryOverlay.vue
This reduces the modal padding for short screens, so all of the gallery is displayed
=> [F] Better padding for gallery overlay on short devices

.github/CODEOWNERS
Just adding Juan to the list of codeowners, so that Panda bothers him as well!
=> [T] Add Juan as a codeowner

src/components/gallery/HdGallery.vue, src/components/gallery/HdGalleryOverlay.vue
https://homeday.atlassian.net/browse/CE-845
I have removed some `pointer-events` so that in most cases the gallery overlay receives the click.
I did not touch the vue zoomer since on mobile we use the whole area for pinch and zoom as well as swiping.
=> [F] Close gallery overlay on esc or overlay click

.travis.yml
Hey team,
this is now publicly published library, so I though to change our deploy to `master` branch. The reason for this is, that if we keep deploying on `develop`, our library actual released state (`master`) and our storybook demo (`develop`) will get temporary out of sync. That is not ideal. So the docs should always show ready to use version and be updated with releases. 
What do you think? Do we need more envs? We can also opt in again for local deploy, so if you need to showcase the changes before going live, you can deploy on demand to s3. 
With this PR I'd like to open discussion on that.
=> [T] Update demo branch

src/components/form/HdInput.vue
We weren't emitting those events and as the `input` is wrapped into a `div` it wouldn't just work adding the listeners in the parent.
=> [F] Emit 'blur' and 'focus' from HdInput

src/components/form/HdInput.vue
That way we can dynamically bind `type` to the input.
=> [F] Watch type on HdInput

vue.config.js
Currently our storybook doesn't work on IE11.
As we are directly consuming the raw components from `vue-zoomer` (the same way we do for Blocks' components in other projects), this dependency needs to be transpiled as it contains ES6 code.
=> [B] Transpile Vue-Zoomer to work on IE11

.dependabot/config.yml
We forgot to add this one to the configuration file (we had it before in the UI config).
It's used by Pull Reminders to ignore bot PRs.
=> [B] Add default labels to dependabot PRs

.coveralls.yml
As repo is now public, we don't need a token anymore, or a pro service. :clap:
=> [T] Remove coverall token

src/styles/buttons.scss
Since using the font mixin with 'link' argument changes the hover text color, we need to put in the btn--primary and btn--secondary :hover state style to block the desidered behaviour
=> [F] hover text color for btn--primary and btn--secondary

src/components/HdAlert.vue, tests/unit/components/__snapshots__/HdAlert.spec.js.snap
Since we are displaying the slot, we should have it inside of a div instead of a p. So if we have a paragraph in the slot, we will not nest paragraphs.
=> [F] HDAlert message in a div instead of in a p

src/components/form/HdInput.vue, tests/unit/components/form/HdInput.spec.js, tests/unit/components/form/__snapshots__/HdInput.spec.js.snap, tests/unit/components/tooltip/__snapshots__/HdTooltipped.spec.js.snap
LastPass breaks UX, especially with our collapsible forms.
Ignoring it can be done easily by adding this attribute : **data-lpignore="true"**
=> [B] Ignore LastPass extension from auto filling inputs

src/components/form/HdGoogleAutocomplete.vue, tests/unit/components/form/HdGoogleAutocomplete.spec.js
- I noticed this use case while implementing validation for location searches. I had to programmatically set errors to the input reference. 
- The idea is to allow to declaratively configure validations for an input like so:
```
props: {
...
customValidators: [
(value) => ({ isValid: value.length >= 10, errorMessage: 'should be at least ten characters long' })
],
},
```
- Please let me know your thoughts. If you think it's a good idea, I'm happy to add async validation support as well as support the generic  `HDInput`
=> [F] Support custom validators for google autocomplete input

src/components/gallery/HdGalleryCarousel.vue
https://homeday.atlassian.net/browse/FET-133
This one is a bit strange, would appreciate more input here. What I've notice is that `change` event is called only when we are at the end of the carousel and index reported in the event is always wrong (`0` or `1`). 
I assume, as we're handling index outside of here, that when we're looping through the images, the flickity is not aware of the changes and kicks in when carousel needs to move and therefore screams the wrong index. 
Disclaimer: I'm not that familiar with Flickity, however look at the docs, our `change`, is definitely not behaving as expected - https://flickity.metafizzy.co/events.html#change and example here: https://codepen.io/desandro/pen/ZxpMdY
I think we might want to look in to this deeper. For the time being, I think this …
=> [B] Fix HdGallery & HdGalleryCarousel

package-lock.json
I do always recommend to use [`npm version`](https://docs.npmjs.com/cli/version.html) to release a new version instead of manually updating the package version.
=> [B] Update package version in package-lock

src/components/gallery/HdGalleryCarousel.vue
https://homeday.atlassian.net/browse/FET-144
This should fix the issue we were having, and it doesn't make use of the breakpoints :)
We basically check how many images we are showing per slide, if it's `1`, then we consider the carousel to be the main gallery, so it controls the current index.
=> [B] Fix the gallery's carousel when showing one item

src/components/form/HdSplitInput.vue, src/styles/inputs.scss
Some context: https://homeday.atlassian.net/browse/FET-140
---
Currently we keep a darker background once the input is filled. As discussed between us and designers it is not the desired state once we don't even keep it like that in Figma.
To avoid conflicts between Figma designs and implementation we agreed on removing the darker background.
=> [T] Remove input filled darker background

.github/workflows/changelog.yml
https://homeday.atlassian.net/browse/FET-137
You can find the source of action here: https://github.com/homeday-de/github-action-changelog-generator
There's still some debt to solve there, I'm tracking it with issues atm. Can be for version 2. :) 
There are some assumptions made in this action, that you can find here: https://github.com/homeday-de/github-action-changelog-generator/blob/develop/README.md
For testing purposes I pushed the branch to `upstream` as well and open a PR directly to `master`. You can see the result here #358 . It will look nicer, once we start following the conventions. Docs to follow (not in this PR).
Open for feedback.
=> [T] Add changelog action

README.md
https://homeday.atlassian.net/browse/FET-136
This PR adds documentation for release process and contribution. 
Please let me know if this is clear enough.
You can see the output version here: https://github.com/SinisaG/homeday-blocks/tree/docs/release#contribution-guide (easier to read)
=> [T] Add contribution and release documentation

src/components/form/HdDynamicForm.vue, tests/unit/components/form/HdDynamicForm.spec.js
Just a small enhancement.
In some cases you may want to check the validity of the form manually, without submitting it (we have this case in Realtor app).
So I added the `validate` method, which complies to the from fields API (can be called by the parent, and returns `true` if the form is valid, and `false` if not).
=> [F] Add a `validate` method to HdDynamicForm

src/components/HdAlert.vue
@viniciuskneves discovered this bug:
As you can see when the message goes to more than one line, the icon shrinks (it should stay 24px*24px). This PR fixes that.
=> [B] Don't shrink HdAlert icons

.github/workflows/publish.yml
I left this code hoping that one day will start supporting Github Packages, but now I don't see us doing it anytime soon, especially after Github acquiring NPM (let's see what happens), so this code is giving us nothing but a failed action.
=> [T] Don't try to publish to Github packages

package-lock.json, package.json, src/components/gallery/HdGalleryMedia.vue
Hi Guys,
We were living a problem with the HD Gallery Media component on the expose pages. The problem was about image loaded function. The image's loaded function was working without loaded (https://youtu.be/dEJPW-9Lo8k). So, the function wasn't working properly, for this reason, I checked the 'imagesLoaded' dependency and the code does a couple of different controls for image load statements.
1. img's `naturalWidth` check:
https://github.com/desandro/imagesloaded/blob/master/imagesloaded.js#L270
2. `load` and `error` events:
https://github.com/desandro/imagesloaded/blob/master/imagesloaded.js#L276
3. `.complete` property control:
https://github.com/desandro/imagesloaded/blob/master/imagesloaded.js#L287
I had doubts that the `.complete` property of the image is not working. There is an …
=> [B] Media Gallery Bug on the Expose Pages

src/components/form/HdRange.vue, tests/unit/components/form/HdRange.spec.js, tests/unit/components/form/__snapshots__/HdRange.spec.js.snap
As a background: we need it in our squad as the labels should be side by side but actually break into specific parts of the word and not randomly.
From the tests, that is the scenario **before** this PR once an `<html>` tag was used:
Now it will look like expected:
I don't think we need to add or update anything in the stories. Let me know if you think we should update something there.
Another question: Shall we do the same for the [tooltip value](https://github.com/homeday-de/homeday-blocks/blob/develop/src/components/form/HdRange.vue#L53)?
=> [T] Allow HdRange labels to be <html>

package-lock.json, package.json, src/components/HdIcon.vue, src/stories/Welcome.vue
The `vue-inline-svg` points to an uncomplied file in its package.json (the `module` property).
So I changed the import path to pick the compiled file. This is not ideal, because we depend on the location of the file (I made sure that we use an exact version), I'm planning to open an issue (or a PR) in their repo, so we can hand this better.
I've also updated the welcome page.
=> [B] Fix the IE11 support

src/components/buttons/HdRadioButton.vue, tests/unit/components/notifications/HdNotifications.spec.js
Changed the label to render html so we can add spans and customize the text.
Changed type to accept objects. That could be the case depending on the project (we have a case like that on sliders).
And the unit test was failing... not sure why, couldn't find any changes related to it...
for some reason the first $nextTick() didn't digest the event all the way before the assert.
=> [F] RadioButton improvements

package-lock.json, package.json
It introduces [Gitmoji CLI](https://github.com/carloscuesta/gitmoji-cli) as default once we're preparing our commit message so we don't need to type a commit message anymore.
Once you run `git commit` (you can do `-a` as well) it will fire [Gitmoji CLI](https://github.com/carloscuesta/gitmoji-cli) and you can follow the steps.
It has basically 3 steps:
- Emoji selection: You can type to search for an Emoji
- Commit title: It is what we usually see on GitHub
- Commit message: It is what is hidden once you click `[...]` on GitHub
~~By default Gitmoji CLI uses a param to know where to write the commit message which I'm setting to `COMMIT_EDITMSG`.~~
~~I've tried with some rebase and it is not the best experience as it tries to add a commit message to every commit squashed for example, but …
=> [F] Gitmoji CLI hook

src/components/form/HdInput.vue, tests/unit/components/form/HdInput.spec.js
Thread: https://homeday.slack.com/archives/C41SHFS5R/p1591690652006900
---
Right now if an input is empty (and not required) it is still validated.
See the GIF below:
- Empty state is not validate first ✅
- Invalid e-mail is validated and error message is shown ✅
- Valid e-mail is validated and error message is removed ✅
- Empty state is validated and error message is shown ❌
The new behavior will validate empty inputs only if they're required, otherwise the validation method is not called.
=> [F] validate only non-empty input value

src/styles/inputs.scss
I've decided to keep the `mixin` inside the `input.scss` file as it won't be used anywhere else.
I've done some research here and decided to implement the same as the official library (https://github.com/material-components/material-components-web/blob/b9776b1d09b9ccfac38b3dc471dee2fd9fc8558a/packages/mdc-textfield/_mixins.scss#L108)
You can read about another approach here: https://github.com/mui-org/material-ui/issues/14427 --> I've also tried it but it just adds complexity for us.
=> [F] Browser autofill behavior

src/components/form/HdInput.vue, src/components/form/HdInputFormatter.vue, src/stories/HdInputFormatter.stories.js, tests/unit/components/form/HdInputFormatter.spec.js
Currently we are validating the value that's being shown in the input, but that shouldn't be the case for HdInputFormatter because we typically want to validate the original value and not the formatted one.
**Example:**
Let's say we want to validate that the value is greater than `1000`, if we have a number formatter (like in the example story), the formatted value will be `"1.000"`, as a string, so our validation won't work because we are comparing a string with a number, that can be solved using parseFloat or similar functions, but parsing `"1.000"` will result in `1` (because of the dot).
This is just an example but don't look at it as the only case.
**Proposed solution**
I'm allowing other components (HdInputFormatter in this case) to use the `validate` method with a desired value …
=> [B] Validate the original value of HdInputFormatter

src/components/form/HdInput.vue, src/stories/HdDashedList.stories.js, src/stories/HdModal.stories.js
Currently if you try to type a decimal number in an HdInput with type "number" you won't be able to do so on webkit browsers (tested on Safari mobile and desktop and Chrome for iOS).
The reason is that when you type a dot to add  the decimal part, webkit browsers emit an `input` event, which is not the case for the modern browsers (take that 🍎!) and will make use parse the new value, so `123.` will immediately become `123`, so the user won't even see the dot.
Before we emit the new value we compare the parsed number if it's the same as the current value, if they are, we don't emit the custom `input` event. This way, the parent won't know about the added dot, but when we add a number after the dot the parsed value will change and that's when we emit the `input` event.
**Example:**
| Input …
=> [B] Allow decimal numbers on webkit browsers

src/styles/inputs.scss
Caught by Percy :purple_heart:
The previous implementation was translating to:
```scss
.field--active .field__label,
.field--double .field__label,
.field--filled .field__label,
.field--select .field__label,
.field__input:-webkit-autofill+.field__label {
font-size:14px;
line-height:18px;
top:5px
}
```
and Firefox was weirdly ignoring the whole block because of the prefix `-webkit-`, even if they are separated with a comma 🤷‍♂️ 
Which resulted in this:
=> [B] Fix the input label on Firefox

tests/unit/components/HdToast.spec.js
Hi team Homeday :)
I think It's better to test the emitted events instead of using mock events. This MR increases the code coverage.
Before:
After:
I'm gradually getting familiar with the project. I look forward to hearing your suggestion on what section of the project is better to work on.
=> refactor HdToast unit test

src/components/HdIcon.vue, tests/unit/components/HdIcon.spec.js, tests/unit/components/__snapshots__/HdIcon.spec.js.snap
Hi!
This PR improves HdIcon accessibility as suggested in https://github.com/homeday-de/homeday-blocks/issues/414
Changes follow the tips on accessible SVGs from the [linked article](https://css-tricks.com/accessible-svgs/) - the title and desc tags are added to the SVG, along with `aria-labelledby` and `role` attributes.
Looking forward to the review 🙂
=> ✨ make HdIcon accessible

src/components/form/HdInput.vue, tests/unit/components/form/HdInput.spec.js
Closes #482 
---
Forwarding all attributes from `HdInput` to `<input>`.
- `autofocus` can be removed, as it will be off by default
- `disabled` could be removed in favor of `:disabled` selector
What do you think about the items above? I wouldn't address them in this PR and open issues instead.
=> [F] Forward attributes from HdInput to <input>

package-lock.json, package.json, src/components/HdLoadingSpinner.vue, src/components/HdTileSelect.vue, src/components/HdTileSelectEditableItem.vue, src/components/HdTileSelectItem.vue
Oops!
*Some context:*
We agreed to use use the `homeday-blocks` alias instead of the `@` because the latter refers to the project's src file.
=> [B] Fix the mixins import path

README.md, package-lock.json, src/components/HdTabsMenu.vue, tests/unit/components/HdTabsMenu.spec.js, tests/unit/components/__snapshots__/HdTabsMenu.spec.js.snap
https://homeday.atlassian.net/browse/CE-1470
- add new property to disable 'focus' pseudo-class
- update tests
- update README.md (set correct node version)
- generate assets
**Before:** Clicking a menu item on the expose page of myHomeday and continue with scrolling doesn't disable the clicked item afterwards.
**After:** By creating the option to remove the 'focus' pseudo-class the automatic scroll can be handled in the correct way.
=> 🐛 [CE-1470] Update HdTabsMenu.vue

src/components/buttons/HdButton.vue, src/stories/HdButton.stories.js, src/styles/buttons.scss, tests/unit/components/buttons/HdButton.spec.js, tests/unit/components/buttons/__snapshots__/HdButton.spec.js.snap, tests/unit/components/form/__snapshots__/HdDynamicForm.spec.js.snap
This PR closes these tickets:
- https://homeday.atlassian.net/browse/CE-1541
- https://homeday.atlassian.net/browse/FET-200
The design team has updated the different states of HdButton, and they are already using it is some designs, which pushes us to customize the component locally as the current FE state do not match the design ones.
- Update the `HdButton` component in Blocks to match the new design specification.
- Create stories to showcase the different states of the component.
- Create tickets to replace the customized buttons with the new component.
- Create / Update Jest snapshots, if needed
- Create tests, if needed
The design and the documentation of the component can be found in [Zeroheight](https://homeday.zeroheight.com/styleguide/s/22414/p/20af8c-buttons/b/65dd3e).
The …
=> [F] [CE-1541] extend HdButton

.storybook/preview.js
In this PR:
Originally, storybook sorts its stories by import order.
- Change storybook configuration file to sort stories alphabetically
| Before | After |
|--------|-------|
| ![image](https://user-images.githubusercontent.com/1855125/91441715-fd303e80-e870-11ea-80cf-d4bf16cbd016.png) |  ![image](https://user-images.githubusercontent.com/1855125/91441595-cb1edc80-e870-11ea-9da3-83b49d4681ad.png)  |
=> [T] Sort stories alphabetically

package.json, src/components/gallery/HdGallery.vue, src/components/gallery/HdGalleryCarousel.vue, src/components/gallery/HdGalleryMedia.vue, src/components/gallery/HdGalleryPlaceholder.vue, src/stories/HdGallery.stories.js, tests/unit/components/gallery/HDGallery.spec.js, tests/unit/components/gallery/HDGalleryMedia.spec.js, tests/unit/components/gallery/HdGalleryCarousel.spec.js, tests/unit/components/gallery/HdGalleryPlaceholder.spec.js, tests/unit/components/gallery/__snapshots__/HDGallery.spec.js.snap, tests/unit/components/gallery/__snapshots__/HDGalleryMedia.spec.js.snap, tests/unit/components/gallery/__snapshots__/HdGalleryCarousel.spec.js.snap, tests/unit/helpers.js
This PR closes ticket [FET-46](https://homeday.atlassian.net/secure/RapidBoard.jspa?rapidView=22&projectKey=FET&modal=detail&selectedIssue=FET-46) and PR #480 
In this PR:
- Create tests for Gallery components
- Fix lint error in some of those components
- Change some css selectors names to avoid using more than one element nesting
- Descending two elements in BEM is not recommended (e.g: `block__element__element2`)
- If we fall in that situation we can:
- Rename the selector to something like `block__element-element2`
- If this doesn't make sense, the component structure need to be re-structured
=> [T] Test Gallery components

src/services/googleAPI.js
- 📌 (GoogleMaps): update to version 3.42
---
I noticed that on MyHomeday a warning was prompting on the console:
After taking a look at the [version documentation](https://developers.google.com/maps/documentation/javascript/versions) of Google Maps, it seems that the only versions considered to be currently supported are: `3.40`, `3.41`, and `3.42`.
So I bumped it to `3.42`.
=> [T] update Google Maps API to version 3.42

src/components/form/HdCheckbox.vue
This PR closes the ticket: https://homeday.atlassian.net/browse/FET-201
I moved the handling of indeterminate state from [customer-app](https://github.com/homeday-de/customer-app/blob/0517ad46b17d4f81a73e651f4323f8ac71ea9347/src/views/panelViews/DocumentsDataRoom.vue#L30) to homeday-blocks.
I didn't add property updates on the checkbox field (as described [here](https://css-tricks.com/indeterminate-checkboxes/)), since it's useful only for default styling purposes, which we don't need.
=> [F] Add indeterminate state to HdCheckbox

src/assets/patterns/dash-pattern-horizontal.svg, src/components/HdDashedList.vue, tests/unit/components/__snapshots__/HdDashedList.spec.js.snap
[REAL-2751](https://homeday.atlassian.net/browse/REAL-2751)
This PR fixes gaps in dashed leaders that appear with multiline titles:
=> [T] Consistency in underlining in the shared valuation results

src/components/HdTable.vue, src/stories/HdTable.stories.js, tests/unit/components/HdTable.spec.js
[DS-102](https://homeday.atlassian.net/browse/DS-102)
Instead of passing the object with component definition to the table through body props, a named slot template has to be defined inside the parent component - with property key as a name (depending on which column we want to have a different layout for):
```
<hd-table :header="header" :body="body">
<template #stars="{value}">
<HdTagsList :items="value"></HdTagsList>
</template>
</hd-table>
```
=> [T] [DS-102] Use slots for nested components in HdTable

src/components/form/HdRadio.vue, src/stories/HdRadio.stories.js, tests/unit/components/form/HdRadio.spec.js, tests/unit/components/form/__snapshots__/HdRadio.spec.js.snap
https://homeday.atlassian.net/browse/DS-108
In this PR:
- Refactor the HdRadio component to match the design system
- Fix CSS order in the component to avoid having complex selectors
- E.g: `.radio:not(:focus):not(#{$r}--disabled) .radio__circle` was removed just by reordering the `disabled state`  classes
- Removed the `label` prop, it was not being used in any project that we have at Homeday (This was confirmed with Magda)
- Update the `HdRadio` javascript to "match" @ilyasmez [pull request](https://github.com/homeday-de/homeday-blocks/pull/559)
- Updated `HdRadio` stories
You can see a preview of the changes here:
https://blocks-storybook-6.netlify.app/?path=/story/components-form-hdradio--default
=> [T] Update HdRadio component with the design system

jest.config.js, src/components/buttons/HdButton.vue, src/stories/HdButton.stories.js, src/styles/buttons.scss, tests/unit/components/buttons/HdButton.spec.js, tests/unit/components/buttons/__snapshots__/HdButton.spec.js.snap, tests/unit/components/form/__snapshots__/HdDynamicForm.spec.js.snap, tests/unit/setup.js
https://homeday.atlassian.net/browse/DS-115
~(This is still in discussion with the design team)~ Done!
- Adjusted the styles of the button in the case of icon only.
- The detection of the icon button case happens automatically thanks to MutationObserver, and it checks the content (text) of the button to decide. I went with this solution instead of a prop to avoid redundancy (we can know based on what we have, so no need for a flag).
- Wrapped HdIcon in a span to always make sure its space is reserved when the svg is being loaded, to avoid layout shifts.
- To avoid recalculating the padding and defining the border every time, I switched to using a pseudo-element (`::before`) to display the border of the buttons, and adjust just it's color based on the variant and the state.
=> [F] Support icon button in HdButton

.github/workflows/deploy-pr-to-s3.yml
To be able to use the build per PR features, make sure to open the PR from a branch in the same repo (not a fork), the same way we do for the other projects.
~If for some reason you want to use your fork, you'll have to add the necessary secrets to your fork (reach out for more details).~
_Update:_ After double-checking the Github Action docs, I found out that it's not possible to use `secrets` nor `env` in the if statement of a job, so that's a deal breaking, so I went for disabling the whole job if the head branch is from a fork.
**This PR**:
- adds a check if the head is from a fork and skips the whole deployment job if it's true;
- fixes the build destination path.
=> [B] Skip the PR deployment for forks

src/components/form/HdCheckbox.vue
The previous [form components refactoring](https://github.com/homeday-de/homeday-blocks/pull/559) didn't include HdCheckbox as we have a ticket for that (@leandroinacio is taking care of it), and that broke the error styles of that component.
This PR just brings back the old styles (without following the new design or using `FieldBase`), so we don't have it broken and can publish a new version whenever we want.
**Before the fix:**
**After the fix:**
=> [B] Bring back the error styles to HdCheckbox

src/components/HdTimeslots.vue, src/stories/mocks/generateTimeSlots.js
In this PR:
- Fix typo in `HdTimeslots` component from `isAvialable` to `isAvailable`
=> Fix isAvailable typo in HdTimeslots

src/components/HdCalendar.vue, tests/unit/components/HdCalendar.spec.js, tests/unit/components/__snapshots__/HdCalendar.spec.js.snap
In this PR:
- Change `HdCalendar` component to enable all days
- Rename prop `disabledIndexes` to `disabledDates`
All those changes are required for the ticket:
https://homeday.atlassian.net/browse/REAL-2412
And the exposé preparation module is the only one using the `HdCalendar` component for now.
This component will face a massive refactor afterwards to be completely usable.
=> [T] Change calendar component to support disabled dates

src/components/form/TextFieldBase.vue
In this PR:
- Fix HdInput bug
- Since we don't specify the clear button type, when the input is in a form if a user hits enter, the clear button is triggered instead of the submit
What is happening:
- When we don't specify a `type="button"` in a `<button>` tag, when the user hits enter, it will "click" the closest button AND submit the form
- If we have a form like this:
``` html
<form>
<div>
<input type="text">
<button type="button" onclick="alert('BLA')">BLA</button> 
<button onclick="alert('CLEARED')">CLEAR</button> 
</div>
<button type="submit">Submit</button>
</form>
```
- When a user fills the input and press `enter`, the alert `CLEARED` will be displayed
- And the form would be submitted
=> [B] Fix HdInput component to not clear on enter

package-lock.json, package.json, src/components/form/TextFieldBase.vue
In this release:
- Fix HdInput bug
- Since we don't specify the clear button type, when the input is in a form if a user hits enter, the clear button is triggered instead of the submit
For more details, check [this link](https://github.com/homeday-de/homeday-blocks/pull/603)
=> [RELEASE] Fix HdInput component to not clear on enter

src/styles/main.scss
Currently while building it prompts the following warning:
That is because we are trying to use elevations from `0` to `11`.
=> 🐛 (Elevations): make sure to create the elevations from 0 to 10

src/components/form/TextFieldBase.vue
Hey All!
We were discussing the new Input Reset Button feature of homeday-blocks with @metal-gogo and we realized that there is a small missing point regarding input statements on the implementation. This is our meeting’s outcome with @metal-gogo 
* Implementation says the clear button should be shown when the user starts to type something on the input. (https://prnt.sc/vhi0tg).
* The design indicates that the clear button should be shown when there is an error and the input is focused (https://homeday.zeroheight.com/styleguide/s/22414/p/601cda-inputs)
At the moment, we are showing the clear button whenever the field doesn’t show a validation check, and the field is focused. We must show the clear button only when there is an error, and the input is focused. :warning:
=> [B][CE-2164] HDInput Active Statement 

package-lock.json, package.json, src/styles/deprecated_font.scss, src/styles/main.scss
The warning was showing for every case `font()` is used, and you can imagine how many times it's currently used in big projects.
That was causing too much noise and made our logs very long which was causing Travis builds to fail due to the 4mb logs limit.
I tried to suppress the warnings on the projects level, but sass-loader doesn't support passing the `quiet` flag :/
I went for a softer version now. And we can go back to the aggressive warning after giving the developers some time to migrate to the new typography.
I wish Sass had a `@warn-once` rule .
=> [T] Reduce the typography warning noise

src/components/form/HdTextarea.vue, tests/unit/components/form/__snapshots__/HdTextarea.spec.js.snap
https://homeday.atlassian.net/browse/FET-243
Currently, when a user clicks in HdTextarea it shrinks and becomes very small becasue of the injected Grammarly element.
As a fix I added `data-gramm_editor="false"` to disable Grammarly for textarea.
=> [B][FET-243] HdTextarea broken by Grammarly

src/components/form/HdForm.vue, src/stories/HdForm.stories.js, tests/unit/components/form/HdForm.spec.js
I added a new watcher and emitted event to HdForm because we need a way to track if the form has been changed in parent component.
Our specific use case is that we want to confirm with the user if he really wants to leave an unfinished flow via modal, and for that we need to know about the changes.
=> [T] Add hasChanged prop to HdForm to make tracking changes easier

.github/workflows/announce-release.yml, .github/workflows/deploy-pr-to-s3.yml, .github/workflows/release.yml
There was a problem with the previous implementation, as I wasn't installing the dependencies before running `npm run semantic-release`.
I've also restructured all the workflows (made sure the steps have a descriptive name and added a comment to describe each workflow).
I've adjusted the `announce-on-slack` workflow to use the `release` event payload instead of fetching the latest release manually.
=> 👷  Fix the release workflow and restructure the others

.dependabot/config.yml
To make it compliant with out workflow.
=> 🔧 Add Gitmoji prefix to Dependabot's commits

src/components/HdDashedList.vue
https://homeday.atlassian.net/browse/REAL-3395
The issue was that the values were not shown for items where there was no primary vaue, but secondary value was present. I adjusted the styles to fix the issue.
=> 🐛 fix mobile HdDashedList styles

src/components/form/HdCheckbox.vue, tests/unit/components/form/HdCheckbox.spec.js
https://homeday.atlassian.net/browse/CA-2944
Fixed an undefined pointer on HdCheckbox, when it tries to focus and the element ref is not there.
=> 🐛 Fix undefined pointer on HdCheckbox

src/services/on-resize.js
This PR makes sure that the `window` object is defined before calling its methods.
The `window` object is only defined on the client side.
That's the only blocking case I've found so far, we might discover some other component-specific cases later and we have to tackle them separately.
We want to use homeday-blocks in a Nuxt project.
=> ✨ Make the library server-side renderable

.travis.yml
We're having a deployment issue because the secret was hard-coded, and we forgot to update it when regenerating the credentials of the AWS user.
To have a single source of truth for all the AWS credentials, I've moved them to [Travis's dashboard](https://travis-ci.com/github/homeday-de/homeday-blocks/settings), to match what we have in the other projects, and to make it easy for Michele to update the credentials whenever he regenerates them.
=> 👷 Update AWS credentials

src/components/HdTable.vue, src/stories/HdTable.stories.js
While implementing the [hd-connect dashboard](https://github.com/homeday-de/hd-connect/tree/REAL-3614/dashboard) had the need to access the context of the columns within the cell slot, so we added it.
=> ✨ Pass row context to the table cell slot

src/components/HdModal.vue
The bottom of the modal wasn't showing properly on mobile devices because of the browser's menu. We added a buffer to the padding of the modal to change the position a bit.
=> 🐛  HD Modal Mobile Alignment Bugfix

.github/workflows/announce-release.yml
It uses the recently created GitHub Action to post releases on Slack: https://github.com/homeday-de/slack-release-bot-action
We have this `curl` in two places already (Sliders and Blocks) and it might be used by other projects so instead of having copy-paste everywhere we can have a single source of truth.
There is one difference: the action uses a `divider` between title and body.
=> 👷 use slack-release-bot-action

src/components/HdModal.vue, tests/unit/components/HdModal.spec.js
----
This is the outcome of the last [Design system sync](https://homeday.atlassian.net/wiki/spaces/PE/pages/2209218870/2021-07-21+Design+System+Inactive+icons+focus+toast). so clicking on overlay should close the HdModal.
> Our modal definitely needs to be updated so that it automatically closes when the user clicks anywhere outside of it.
=> ✨ Add closing event on HdModal Overlay

src/services/utils.js, tests/unit/services/utils.spec.js
https://homeday.atlassian.net/browse/VIEW-291
We are using `keysToCamelCase` & `keysToSnakeCase` helper functions in customer-app and Sliders. 
As @viniciuskneves 's [suggestion](https://github.com/homeday-de/sliders/pull/1700#pullrequestreview-714678698)
It makes sense to move them to Blocks and have a single source of truth.
Reference from customer-app: 
- [src/services/utils.js#L105-L141](https://github.com/homeday-de/customer-app/blob/develop/src/services/utils.js#L105-L141)
- [tests/unit/services/utils.spec.js#L323-L333](https://github.com/homeday-de/customer-app/blob/develop/tests/unit/services/utils.spec.js#L323-L333)
Will create a tech debt ticket to migrate those current functions to use the helper functions from Blocks in customer-app. 
Of course, after we upgrade homeday-blocks …
=> ✨ Add keysToCamelCase & keysToSnakeCase helper function into UtilsService

package.json
Webpack is doing a bad job at tree-shaking our library. If you check the builds of your projects you'll see that all the components are included, even the ones that are not being used.
So we have to help Webpack a bit, first by providing a `module` entry, because we are using ES modules, and defining any side effects.
I kept `main` as well, because it's needed when running tests as this is how `@vue/babel-preset-app` is configured, see: [modules](https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/babel-preset-app#modules).
I've set the `sideEffects` to `"*.vue"` so we can also include the the styles of the component (it doesn't include all the styles, just the ones that the component depend on).
_That took me quite some time to figue out, even gave me side effects personally 😆   I …
=> 🔧  Use the library as an ES module and define the side effects

package.json, src/stories/Welcome.vue
After the [previous release](https://github.com/homeday-de/homeday-blocks/pull/794) we had a problem with global styling inside Storybooks:
To fix that, we added this property to include `main.scss` file into blocks context.
- This is not actually a good thing since every component should contain its own styles and not depend on global/external styles, and we should at some point in time refactor that
- For now, we added this "quick fix" to always include the global styling in blocks, but the tree shaking will continue to work in other applications
- We also added one extra instruction step inside our "Welcome" story to warn the user that they must include the global styling
=> 🐛 Add main.scss file to package.json sideEffects prop

src/components/buttons/HdButton.vue
Added `scoped` attribute to HdButton styles to fix the issue of "icon button" styles being overridden with the button styles defined in `/src/styles/buttons.scss` (loaded with `main.scss`). 
Having styles scoped increases specificity for icon buttons and fixes the layout to be as expected.
Before:
=> 💄 Scope HdButton styles

src/components/HdCalendar.vue, src/components/HdModal.vue, src/components/HdToast.vue, src/components/buttons/HdArrowButton.vue, tests/unit/components/__snapshots__/HdCalendar.spec.js.snap, tests/unit/components/__snapshots__/HdModal.spec.js.snap, tests/unit/components/__snapshots__/HdToast.spec.js.snap, tests/unit/components/buttons/__snapshots__/HdArrowButton.spec.js.snap
Buttons should have an explicit `type` attribute defined, otherwise, if we add this component inside of a form, the button will automatically behave like a submit button.
This PR is to fix a problem with our current task: 
> we are rendering the `HdCalendar` inside of a form, but when we click on the "arrow button" inside of the calendar, it is triggering a form submission.
We took advantage and also added a `type="button"` for other general components.
=> ♿️ Add type button for Calendar, Modal, Toast and ArrowButton components

.releaserc.js
This PR includes a fix to properly compare the Gitmojis to avoid [this issue](https://github.com/homeday-de/homeday-blocks/runs/4190894388?check_suite_focus=true).
The PR from @kuroski surfaced a little issue we have with the automated releases.
The issue was because when the script was trying to compare the two strings with `===` and that didn't work, you can test it yourself:
```js
'♿️' === '♿'; // false
```
If you debug deeper you'll see that the first string has a length of `2` instead of one, and the reason is having a hidden character ([(VARIATION SELECTOR-16)](https://www.fileformat.info/info/unicode/char/fe0f/index.htm) which is used to select a variant of an emoji, like gender or skin color). We can also use `String.charCodeAt(0)` to compare just the first character of the string …
=> 👷  Semantic releases: Fix the way we compare gitmojis

src/components/form/HdInputPhone.vue
In this PR [HdInputPhone ](https://github.com/homeday-de/homeday-blocks/blob/master/src/components/form/HdInputPhone.vue)component `flag-icons-svg` styles were fixed because they were being imported with relative paths that can't be resolved when using homeday-blocks in other projects.
=> 🐛 Fix flag-icons-svg styles import paths in HdInputPhone

package-lock.json, package.json, scripts/build.js
**Why limit build script concurrency?**
Because it was too much for the Github-hosted runners which are used to run actions (2-core CPU / 7 GB RAM)
- Added [p-limit](https://www.npmjs.com/package/p-limit) as a dev dependency
- Used `p-limit` to limit the build script concurrency based on the number of CPU cores
=> ⚡️ Limit build script concurrency 

src/stories/HdSplitInput.stories.js
This PR would fix the issue: storybooks HdSplitInput icon wouldn't show up and you couldn't change it either.
=> :bug: Bind HdSplitInput story icon to knobs

package-lock.json, package.json
Upgrade to the latest homeday assets and trigger Storybook build
Fix arrow-back overwriting arrow flagged by @ivandata on Slack https://homeday.slack.com/archives/CMQ63UMD0/p1648479929348739
=> :arrow_up: Bump home-assets from 4.41.0 to 4.43.0

package-lock.json, package.json
Upgrade to the latest homeday assets and trigger Storybook build
=> :arrow_up: Bump home-assets from 4.43.0 to 4.49.0

scripts/build.js
Include both JS & TS component types and services in the build script input files because `src/components/tooltip/HdTooltipInstaller.js` wasn't built even though it is needed in customer-app
=> ♻️ Include both JS & TS component types and services in the build script input files

src/components/buttons/HdButton.vue, src/styles/buttons.scss
Removing unnecessary button style's scoped attr that breaks customer-app tests, scoped was originally add to prioritize the button icon padding override. 
https://github.com/homeday-de/homeday-blocks/pull/797
=> :bug: Remove button style's scoped attr, since this breaks products tests

package-lock.json, package.json, vue.config.js
After vue cli builds, the customer app and slider cannot resolve the imported assests
This one temporarily embed the svgs and unblock merging latest homeday-blocks into other products
=> :package: Embed imported homdeday-assets icons

package-lock.json, package.json
The dependencies  used for our release workflow were updated because sometimes the workflow doesn't work as expected with some Gitmoji's like ♻️ 
/
- Upgrade semantic-release-gitmoji to v1.4.4
- Upgrade semantic-release to v19.0.2
=> ⬆️ Upgrade semantic-release & semantic-release-gitmoji dependecies

src/services/googleAPI.js
- On `customer-app`'s search page, there's a weird bug that causes the exact same Google Maps JS SDK imported and loaded for more than one time.
- Ticket: https://homeday.atlassian.net/browse/VIEW-734
- Sentry: https://sentry.io/organizations/homeday-de/issues/3186419210/
- GitHub Issue: #958 
- 🐛 Check is the Google Maps JS SDK script already imported or not
=> 🐛 [VIEW-734] Prevent Google Maps JS SDK from importing more than one time

src/services/googleAPI.js
In this PR the Google Maps API existence check condition was fixed because it is not accurate as you can see in the related bug ticket.
[VIEW-821](https://homeday.atlassian.net/browse/VIEW-821)
- Fix Google Maps API existence check condition
- Use [GMaps API quarterly release channel ](https://developers.google.com/maps/documentation/javascript/versions)because **v3.42** is retired ( since the channel is updated once per quarter it is the most predictable)
=> 🐛 Fix Google Maps API existence check condition

src/components/form/HdDynamicForm.vue
According to the conversation [here](https://homeday.atlassian.net/browse/VIEW-708?focusedCommentId=33539), we want to format user entries for area and price on search widget
=> :sparkles: Add support to dynamic forms for input formatter

.github/CODEOWNERS, src/styles/typography.scss
This PR is about fixing a typo in the **DS-60** font-size because it should be **8** instead of **12** pixels as specified in the [DS documentation](https://ds.homeday.dev/058baf035/p/453cf2-typography/b/55e546).
- [✏️ Fix typo in DS-60 font-size](https://github.com/homeday-de/homeday-blocks/commit/0a362d4bbc5c500ebebccb171ff4e71083c48b37)
- [🎉 Add Victor & Ola to CODEOWNERS](https://github.com/homeday-de/homeday-blocks/pull/993/commits/a08ec09841bd2604dac93b0924c1ccf2225ef71e)
=> ✏️ Fix typo in DS-60 font-size

README.md
In this PR I added workflow status badges for [the release and publish](https://github.com/homeday-de/homeday-blocks/blob/master/.github/workflows/release.yml) and [the storybook deployment](https://github.com/homeday-de/homeday-blocks/blob/master/.github/workflows/deploy-storybook.yml) workflows, so we can easily spot when they are failing.
- [📝 Add workflow status badges](https://github.com/homeday-de/homeday-blocks/commit/a96b9529319fec57863a479a6301c1d327771070)
=> 📝 Add workflow status badges

src/components/gallery/HdGallery.vue, src/components/gallery/HdGalleryCarousel.vue, src/components/gallery/HdGalleryMedia.vue, src/stories/HdGallery.stories.js, src/stories/mocks/GALLERY_ITEMS.js, tests/unit/components/__snapshots__/HdLazyImage.spec.js.snap, tests/unit/components/gallery/HDGallery.spec.js, tests/unit/components/gallery/__snapshots__/HDGallery.spec.js.snap, tests/unit/components/gallery/__snapshots__/HdGalleryCarousel.spec.js.snap, tests/unit/components/gallery/__snapshots__/HdGalleryTiles.spec.js.snap
[CA-3824](https://homeday.atlassian.net/browse/CA-3824)
According to this task, we need to add video support to the HdGallery component.
- An iframe will be added to the HdGalleryMedia, if a video is provided.
- A new prop is also added to the HdGallery called `mobileCounterBadge` to show a counter in mobile view.
=> ✨ Add video support to HdGallery

src/components/gallery/HdGallery.vue, src/components/gallery/HdGalleryCarousel.vue
When resizing the page, the `currentItemIndex` somehow reset to `NaN`. This causes the carousel previous/next button not working after resize, as well as `gallery__info` showing “NaN/10”
https://user-images.githubusercontent.com/4544770/179506595-f2a74769-b597-402f-8123-2a7c001a767a.mp4
Making sure when updating the current index value, it’s not returning `undefined`. This can be fixed by changing `itemIndex` to `itemIndex || 0` so it will always return a valid number.
[VIEW-927](https://homeday.atlassian.net/browse/VIEW-927)
- 🐛 Added fallback value (`0`) when updating `currentIndex` value to prevent `undefined`
=> 🐛 [VIEW-927] Fix hd-gallery current index NaN

package-lock.json, package.json, src/services/scrolling.js
Replace `naturalScroll.scrollTop(scrollEl, scrollPosition)` with `scrollEl.scrollTo({ top: scrollPosition, behavior: 'smooth' })`
Also, the [library](https://www.npmjs.com/package/natural-scroll) is seriously outdated:
[VIEW-930](https://homeday.atlassian.net/browse/VIEW-930)
- Removed `natural-scroll`
- Replaced with `scrollEl.scrollTo({ top: scrollPosition, behavior: 'smooth' })`
- ~Try to use `scrollIntoView` if possible, so no need to calculate the scroll position manually~
=> ♻️ [VIEW-930] Remove natural-scroll and replace with native scrollTo

.github/CODEOWNERS
In this PR, I removed the people who left 😿 and added the new teammate [Tim](https://github.com/logycode) 🎉.
=> 🔧 Update CODEOWNERS

src/components/details-table/HdDetailsTable.vue, src/stories/HdDetailsTable.stories.js
Adds support for a reference to target separate instances of Hd Details Table. A requirement for: [#REAL-4538](https://homeday.atlassian.net/jira/software/c/projects/REAL/boards/7?modal=detail&selectedIssue=REAL-4538) to work.
=> ✨  Add reference to hd details table

src/components/details-table/HdDetailsTable.vue, src/stories/HdDetailsTable.stories.js
In myHD we need to be able to add a CTA after a details table, e.g.:
- Add after slot support in HdDetailsTable
- Add before/after slots in HdDetailsTable story
=> ✨ Add after slot support in HdDetailsTable

package-lock.json, package.json, src/components/gallery/HdGallery.vue, src/components/gallery/HdGalleryCarousel.vue, src/components/gallery/HdGalleryMedia.vue, src/stories/HdGallery.stories.js
TL;DR: Allow user to click on the carousel item to navigate to other page using `router-link`.
The previous method was using Flickity's `staticClick`. However, this method won't work if the user want to open the link in new tab (by holding the Cmd/Ctrl button), or right click then select "Open Link in New Tab".
This can be done by using `router-link`. If there's no link, then the carousel item will fallback to `div`.
https://user-images.githubusercontent.com/4544770/183681412-7096a95d-e1b9-4295-a177-15fba46a8eb1.mov
[VIEW-1078](https://homeday.atlassian.net/browse/VIEW-1078)
https://github.com/homeday-de/customer-app/pull/2917
- myHD: https://frontend-pulls.homeday.de/customer-app/2917
- Storybook: https://frontend-pulls.homeday.de/homeday-blocks/1011/
- ✨`HdHallery`: Added `to` prop
- …
=> ✨ [VIEW-1078] Allow user to click on the carousel item to navigate to other page using "router-link"

.github/workflows/release.yml, .releaserc.js
In order to test new features, we better have a pre-release setup. It can be achieved by publishing Beta/Alpha/RC versions. Since the beta versions can do the job, I set up the configuration to support beta versions only.
Read more: https://github.com/semantic-release/semantic-release/blob/7b7728c33c65ba801cd3bc6162cef4871b4ea0f5/docs/usage/configuration.md#branches
=> :wrench: Add pre-release configuration

src/components/form/HdGoogleAutocomplete.vue
Sentry: https://sentry.io/organizations/homeday-de/issues/3529944572/
1. Go to myHD expose search page
2. Type “00000” (or any invalid zip code), then click on the search button
3. Visually there’s no error, but if you look at the console, then you will see this error message:
> TypeError: Cannot read properties of null (reading '0')
`getLocation` should return object that looks like this:
```
{
lat: null,
lng: null,
name: this.value,
}
```
The `getLocation` is returning 2 objects if the Geocoder status is NOT OK due to missing `return` in the function.
---
[VIEW-1151](https://homeday.atlassian.net/browse/VIEW-1151)
- 🐛 Add `return` to HdGoogleAutocomplete getLocation function
=> 🐛 [VIEW-1151] Add return to HdGoogleAutocomplete getLocation function

.github/workflows/ci.yml, package-lock.json, package.json, src/components/form/HdCheckboxCard.vue, src/components/form/HdCheckboxCardGroup.vue, src/components/form/HdRadioCard.vue, src/components/form/HdRadioCardGroup.vue
I upgraded our TS version from 4.1.x to 4.8.x then changed it to 4.5.x.
So, we had some issues that were not clear enough in the console, so I downgraded to have better errors. feel free to upgrade to the latest version when the problem is fixed.
From:
To:
Right now, TS errors are only visible in our IDs, even the ts build process can't build .vue files so we can't receive any TS issues from vue files. Therfore we need something like "tsc --noEmit" but for checking ts errors in .vue files.
I added a package that can do the same for our Vue files and added it to our CI process.
I also tried [this package](https://github.com/vuedx/languagetools/tree/main/packages/typecheck) but doesn't work properly.
And finally, made the build process work as expected.
=> :bug: Fixed TS issues and added type checking tool to the build process

.releaserc.js
- Fix `dateformat` import error which occurred in [the last release job](https://github.com/homeday-de/homeday-blocks/actions/runs/3112556015/jobs/5046105734#step:7:13) after it was upgraded to v5.
=> :rotating_light: Fix dateformat import error

.github/dependabot.yml, .releaserc.js, package-lock.json, package.json
Reverted `dateformat` upgrade since it breaks the release and publish workflow.
- Revert "⬆️ Bump dateformat from 4.5.1 to 5.0.3 (#915)" 
- Revert "🚨 Fix dateformat import error (#1048)" 
- Configure dependabot to ignore dateformat upgrades
=> ⏪️ Revert dateformat upgrade

package-lock.json, package.json, src/stories/Welcome.vue
[FET-252](https://homeday.atlassian.net/browse/FET-252)
- Bump `eslint-plugin-vue` from 7.14.0 to 9.5.1
- Bump `@vue/test-utils` from 1.2.1 to 1.3.0
- Bump `@testing-library/jest-dom` from 5.14.1 to 5.16.5
- Bump `babel-loader` from 8.2.2 to 8.2.5
- Remove `node-fetch` since it is not used anymore
- Remove `dotenv` since it is not used anymore
- Fix lint error `vue/multi-word-component-names` in Welcome story component
---
Closes #963, #1009, #1054, #1060
=> ⬆️ Upgrade eslint-plugin-vue, @vue/test-utils, @testing-library/jest-dom & babel-loader

src/styles/typography.scss
When trying to use the latest blocks version in [myHomeday](https://github.com/homeday-de/customer-app/pull/3038), all checks passed except the PR deployment action which failed with [the error](https://github.com/homeday-de/customer-app/actions/runs/3376982506/jobs/5605745877#step:7:112):
> Error: CSS minification error: Lexical error on line 1: Unrecognized text.
Erroneous area:
1: $size / 16
Which is simply fixed by wrapping `#{$size}` (Check [Sass interpolation docs](https://sass-lang.com/documentation/interpolation))
https://github.com/homeday-de/customer-app/pull/3038
=> :bug: Fix CSS minification error in consuming projects PR deployment action

src/components/tooltip/HdTooltipInstaller.js
- Use the consuming project's Vue instance instead blocks own instance to register the directive to ensure that it gets registered even if their Vue version doesn't match ours.
=> :bug: Fix unresolved hd-tooltip directive in consuming projects

.github/CODEOWNERS
- Update `CODEOWNERS` according to the latest Homeday frontend team setup.
=> 🔧 Update CODEOWNERS [skip ci]

src/styles/mixins.scss
Tested as suggested by @aym3nb https://github.com/homeday-de/website/pull/1531#issuecomment-1340926758
This time it works 😊
```
ERROR in ./node_modules/homeday-blocks/src/components/form/HdRange.vue?vue&type=style&index=0&id=f46fdbec&prod&lang=scss& (./node_modules/css-loader/dist/cjs.js??ref--7-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/dist/cjs.js??ref--7-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--7-oneOf-1-3!./node_modules/sass-resources-loader/lib/loader.js??ref--7-oneOf-1-4!./node_modules/@nuxt/components/dist/loader.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/homeday-blocks/src/components/form/HdRange.vue?vue&type=style&index=0&id=f46fdbec&prod&lang=scss&)
Module build failed (from …
```
=> :bug: Fix the "cannot divide by px" issue

src/components/form/HdRadio.vue, src/stories/HdRadio.stories.js, tests/unit/components/form/HdRadio.spec.js, tests/unit/components/form/__snapshots__/HdRadio.spec.js.snap
There are some cases when I need to render options with a bold text inside the label of a radio buttons.
That was not allowed before, so I changed the label inside the Radio Items to allow raw HTML as a prop.
=> ✨ Allow raw html on the labels of the radio items

src/components/form/HdRange.vue, src/stories/HdRange.stories.js, tests/unit/components/form/HdRange.spec.js
[TOFU-5447](https://homeday.atlassian.net/browse/TOFU-5447)
To be able to implement a page change in realtor app, matching the Figma layout.
Currently, bullets are always even steps (which means, they show up every 1 step).
In some cases, most of the bullets are even, but one option (the default one) differs.
To achieve that, we offer a new prop, an array receiving the value (in number) of where the steps/bullets should be placed.
That way we can draw the step and move the bullet accordingly to the next accepted step if the user clicks in between them.
You can check the new storybook to better understand it.
I have also updated the storybook file to match the new standard, but all previous stories were kept.
=> :sparkles: Introduce customizable bullets for HdRange

src/components/form/HdRange.vue, src/stories/HdRange.stories.js, tests/unit/components/form/HdRange.spec.js
Found an issue with the custom bullets when using decimals as steps.
This fixes the issue and adds a unit test to cover such scenario.
=> 🐛 Fix custom hd range bullets precision

src/components/HdTagTypes.ts, src/components/HdTagsList.vue, src/index.js, src/stories/HdTagsList.stories.js, tests/unit/components/HdTagsList.spec.js, tests/unit/components/__snapshots__/HdTagsList.spec.js.snap
https://homeday.atlassian.net/browse/TOFU-5523
The new property carousel requires usage of a different type of tag. 
Since we already have the component, I have added a modifier to reuse the code.
=> :sparkles: Adds new tag list modifier

package-lock.json, package.json, src/components/form/HdInputPhone.vue, tests/unit/components/buttons/__snapshots__/HdArrowButton.spec.js.snap, tests/unit/components/buttons/__snapshots__/HdButton.spec.js.snap, tests/unit/components/form/__snapshots__/HdDynamicForm.spec.js.snap, tests/unit/components/form/__snapshots__/HdInputPassword.spec.js.snap, tests/unit/components/form/__snapshots__/HdInputPhone.spec.js.snap, tests/unit/components/form/__snapshots__/HdPasswordConfirm.spec.js.snap, tests/unit/components/form/__snapshots__/HdRange.spec.js.snap, tests/unit/components/form/__snapshots__/HdTagsSelector.spec.js.snap, tests/unit/components/gallery/__snapshots__/HDGallery.spec.js.snap
- Fetch `flag-icons-svg` files from [CDN](https://cdn.jsdelivr.net/npm/flag-icons-svg@0.0.3/) instead of locally to ensure they show up in consuming projects and to avoid increasing HdPhoneInput component size further
- Update outdated snapshots
- Remove `flag-icons-svg`
---
=> 🐛 Fix HdPhoneInput component missing country flag icons
