homeday-de/homeday-blocks

src/components/notifications/HdNotifications.vue, tests/unit/components/notifications/HdNotifications.spec.js, tests/unit/components/notifications/HdNotificationsBar.spec.js, tests/unit/components/notifications/__snapshots__/HdNotifications.spec.js.snap, tests/unit/components/notifications/__snapshots__/HdNotificationsBar.spec.js.snap
https://homeday.atlassian.net/browse/FET-34
Rendering of the actual notifications is already covered by HdNotificationsBar tests, so here I focused on the events fired from the component that we rely on.
=> [T] Add HdNotifications tests

package.json
Two small things: 
- Bump of the version
- Remove private flag
Once merged, I'll publish to npm. Already added you guys as collaborators and we've created the org.  
https://www.npmjs.com/package/homeday-blocks :tada:
=> [T] Bump the version for npm 

AUTHORS, LICENSE, package.json
https://homeday.atlassian.net/browse/FET-93
https://homeday.atlassian.net/browse/FET-94
=> [T] Add license and enhance metadata in package.json

AUTHORS, package.json
Bumping version for #187 . 
@viniciuskneves : Do you want to include #200 ? I'll release tomorrow.
=> [T] Bump version

.travis.yml, package-lock.json
Two small things that were left over. :)
=> [T] Update travis

src/components/HdAlert.vue
I tried using the component and whoops :D For now I'll simply add the icons to the same path in our project, but we need to fix this :)
=> [B] Fix icons reference

package-lock.json, package.json
- Fix icons references in the HdAlert component
=> [Release] HdAlert icons reference fix

package-lock.json, package.json
=> [T] Bump patch version

.dependabot/config.yml
Instead of keeping the configuration on the panel we keep it explicitly here.
I've also updated to run updates weekly instead of daily to avoid some noise (open for discussion).
=> [F] Use dependabot config file

.github/CODEOWNERS, AUTHORS
Added @aym3nb to code owners and authors.
=> [T] Updated code owners and authors

.travis.variables.sh, .travis.yml, README.md, config/storybook/preview-head.html, package-lock.json, package.json, src/components/HdLink.vue, src/stories/HdAlert.stories.js, src/stories/HdArrowButton.stories.js, src/stories/HdButton.stories.js, src/stories/HdCalendar.stories.js, src/stories/HdGallery.stories.js, src/stories/HdGalleryOverlay.stories.js, src/stories/HdGoogleAutocomplete.stories.js, src/stories/HdLazyImage.stories.js, src/stories/HdLink.stories.js, src/stories/HdPasswordConfirm.stories.js, src/stories/HdRadio.stories.js, src/stories/HdSelect.stories.js, src/stories/HdTextarea.stories.js, src/stories/HdTimeslots.stories.js, src/stories/HdToast.stories.js, src/stories/HdTooltipped.stories.js, src/stories/TooltipDirective.stories.js, src/stories/WelcomeStory.js, tests/unit/components/HdLink.spec.js, tests/unit/components/__snapshots__/HdLink.spec.js.snap
It adds Percy snapshots in the build process. It takes screenshots from every story so I added a param to skip the ones with playground and also some with dynamic data. My idea here is to not refactor all components to add screenshot capabilities.
I've also set the width of a specific component that has a different behavior for mobile only.
closes https://github.com/homeday-de/homeday-blocks/issues/226
Upgraded some dependencies to close dependabot PRs.
=> [F] Percy snapshots

package.json
=> [F] Open coverage report after generated

src/components/gallery/HdGalleryCarousel.vue, src/components/gallery/HdGalleryMedia.vue, src/stories/mocks/GALLERY_ITEMS.js, tests/unit/components/HDGalleryMedia.spec.js, tests/unit/components/HdGalleryCarousel.spec.js, tests/unit/components/__snapshots__/HDGalleryMedia.spec.js.snap, tests/unit/components/__snapshots__/HdGalleryCarousel.spec.js.snap
⚠️  There may be bugs or buggy things.
In those components, is now possible to use
- Images with a source
- Images, each one with its own source set
- Picture elements with multiple sources
- Picture elements with multiple sources, each one with its own source set
⚠️ The documentation is still missing, but you can start to review the functionalities.
=> [F] Picture element and source sets on HDGalleryMedia and HDGalleryCarousel

src/components/form/HdDynamicForm.vue, tests/unit/components/form/__snapshots__/HdDynamicForm.spec.js.snap
closes https://github.com/homeday-de/homeday-blocks/issues/204
=> [T] Replace usage of button with HdButton in HdDynamicForm

package.json
Bumping version for new release.
=> [T] Version bump

src/components/gallery/HdGalleryCarousel.vue, tests/unit/components/gallery/HdGalleryCarousel.spec.js, tests/unit/components/gallery/__snapshots__/HdGalleryCarousel.spec.js.snap
The current item index wasn't being updated in HdGallery if the user made the slide with a touch (mobile) because no input event was emitted.
=> [B] current item index doesn't update on touch slide

src/components/form/HdInput.vue, src/components/form/HdInputPassword.vue, src/stories/HdInput.stories.js, src/stories/HdInputPassword.stories.js, tests/unit/components/form/HdInput.spec.js, tests/unit/components/form/HdInputPassword.spec.js, tests/unit/components/form/__snapshots__/HdInput.spec.js.snap, tests/unit/components/form/__snapshots__/HdInputPassword.spec.js.snap, tests/unit/components/tooltip/__snapshots__/HdTooltipped.spec.js.snap
https://github.com/homeday-de/homeday-blocks/issues/203
=> [T] Extract HdInputPassword from HdInput 

.github/CODEOWNERS
No ticket, a config update to add @mlande to codeowners.
=> [T] Added Michael to codeowners

.eslintrc.js, .travis.yml, package-lock.json, package.json, webpack-alias.js
- Update to latest v10 version
- Audit fix dependencies
- Remove eslint-disable-rule
=> [T] Update Node and remove linter ignore setting

src/components/HdLazyImage.vue, src/components/gallery/HdGalleryTiles.vue, src/stories/HdGalleryTiles.stories.js, src/stories/HdLazyImage.stories.js, src/stories/mocks/GALLERY_ITEMS.js, tests/unit/components/HdGalleryTiles.spec.js, tests/unit/components/HdLazyImage.spec.js, tests/unit/components/__snapshots__/HdGalleryCarousel.spec.js.snap, tests/unit/components/__snapshots__/HdGalleryTiles.spec.js.snap, tests/unit/components/__snapshots__/HdLazyImage.spec.js.snap
With a parameter, we can have images elements instead of backgrounds for HdGalleryTiles
=> [F] Gallery Tiles can use images instead of backgrounds

jest.config.js, src/services/README.md, src/services/date.js, src/services/utils.js, tests/global-setup.js, tests/unit/services/date.spec.js, tests/unit/services/utils.spec.js
https://homeday.atlassian.net/browse/FET-84
This PR:
=> [T] Document date service

.travis.yml, main.js, package-lock.json
- Update to Node v10.19
- Export buttons
We could avoid that if we're import from `main.js` so we would make sure that we're exporting all the components.
Gonna work on it afterwards but I do also accept help in case anyone wants to volunteer 😄
=> [F] Export missing components

src/components/gallery/HdGallery.vue, src/stories/HdGallery.stories.js, tests/unit/components/HdGallery.spec.js, tests/unit/components/__snapshots__/HdGallery.spec.js.snap
A feature that I'm going to need soon.
=> [F] HdGallery emits on current item click

.github/workflows/publish.yml
🧪⚗️ Trying Github actions, please don't mind the noise.
=> [T] Add automatic publishing action

.github/workflows/publish.yml, tests/unit/components/HdGalleryTiles.spec.js, tests/unit/components/__snapshots__/HdGalleryTiles.spec.js.snap
- Tests for HDGalleryTiles
- Fix the release action workflow
=> [RELEASE] Fix the release action workflow, Tests for HDGalleryTiles

.github/workflows/publish.yml, package.json
=> [RELEASE] Update the publishing workflow

package.json, src/components/gallery/HdGalleryCarousel.vue
- Fix HdGallery & HdGalleryCarousel components
=> [Release]  v6.0.2

src/stories/HdGallery.stories.js, src/stories/mocks/GALLERY_ITEMS.js, tests/unit/components/__snapshots__/HDGalleryMedia.spec.js.snap, tests/unit/components/__snapshots__/HdGallery.spec.js.snap, tests/unit/components/__snapshots__/HdGalleryCarousel.spec.js.snap, tests/unit/components/__snapshots__/HdGalleryTiles.spec.js.snap, tests/unit/components/__snapshots__/HdLazyImage.spec.js.snap
https://homeday.atlassian.net/browse/FET-139
Improved HdGallery story for proper testing to be able to catch tiny hidden bugs 🐛👀
=> [T] Improve HdGallery story for proper testing

src/components/gallery/HdGalleryCarousel.vue, src/styles/_variables.scss, src/styles/variablesForJS.scss
https://homeday.atlassian.net/browse/FET-133
This is the actual fix of this bug, after trying already in #327 
Would appreciate some input here @homeday-de/frontend-engineering
=> [B] Fix HdGallery & HdGalleryCarousel 

src/components/buttons/HdButton.vue, src/stories/HdButton.stories.js, tests/unit/components/buttons/HdButton.spec.js
https://homeday.atlassian.net/browse/FET-143
=> [B] Forward HdButton listeners

.github/CODEOWNERS
Added @leandroinacio and @volcanioo to codeowners. 
No ticket.
=> [T] Extend codeowners

tests/unit/components/buttons/HdRadioButton.spec.js
https://homeday.atlassian.net/browse/FET-57
Got 100% coverage and added output checks
=> [T] Improve test coverage for HdRadioButton

main.js, src/assets/icons/ic_close--white.svg, src/components/HdModal.vue, src/stories/HdModal.stories.js, tests/unit/components/HdModal.spec.js, tests/unit/components/__snapshots__/HdModal.spec.js.snap
Reusable component moved from myhomeday during PEW 03/2020.
=> [F] Add HdModal

tests/unit/components/form/HdPasswordConfirm.spec.js, tests/unit/components/form/__snapshots__/HdPasswordConfirm.spec.js.snap
https://homeday.atlassian.net/browse/FET-41
=> [T] Write tests for HdPasswordConfirm

src/components/HdModal.vue, src/components/form/HdInput.vue, tests/unit/components/form/HdInput.spec.js
https://homeday.atlassian.net/browse/FET-119
=> [T] Add custom rule support for HDInput

.github/CODEOWNERS
😢 and 😄 at the same time hehehe
=> [T] Remove Juan and add Daniel to CODEOWNERS

src/components/form/HdInputPassword.vue
https://homeday.atlassian.net/browse/FET-163
The visibility toggle has broken after the new assets change.
Check out 👇( type something to actually see it hehe)
https://blocks.homeday.dev/?path=/story/components-form-hdinputpassword--simple
=> [B] Fix HdInputPassword visibility toggle

.github/workflows/publish.yml, package-lock.json, package.json, src/components/HdAlert.vue
<h3>Changelog</h3>
<h4>Bugfixes</h4>
:lipstick: Don't shrink HdAlert icons (#415)<br/>
<h4>Tasks</h4>
🔧 Don't try to publish to Github packages (#418)
=> [Release] Don't shrink HdAlert icons

package-lock.json, package.json, src/components/form/HdRange.vue, tests/unit/components/form/HdRange.spec.js, tests/unit/components/form/__snapshots__/HdRange.spec.js.snap
:sparkles: Allow HdRange labels to be <html> (#422)
=> [Release] Allow HdRange labels to be <html>

package-lock.json, package.json, src/components/gallery/HdZoomerGallery.vue, src/stories/HdGallery.stories.js
Using the picture element we can have smaller images on mobile.
=> [F] Pictures in HdGalleryOverlay Vue-zoomer

.github/CODEOWNERS
=> [T] Remove @mlande from CODEOWNERS

package-lock.json, package.json
Oops, I forgot to bump the version
=> Upgrade to v11.0.1

package-lock.json, package.json
We should indeed automatize the whole publishing process :D You might skip some steps on a slow Tuesday
=> [Release] Version bump 11.0.1

src/components/gallery/HdGalleryMedia.vue, tests/unit/components/notifications/HdNotifications.spec.js
https://homeday.atlassian.net/browse/CA-2366
=> [B] Remove blurred transition of image slide on Gallery

src/components/buttons/HdLoaderButton.vue, src/notes/HdIconFillFromClass.md, src/notes/HdLoaderButton.md, src/stories/HdLoaderButton.stories.js, src/styles/buttons.scss, tests/unit/components/buttons/HdLoaderButton.spec.js
https://homeday.atlassian.net/browse/FET-176
-
Not sure why we had a test expecting to trigger the click when the button is disabled, but if there is a reason we should add some comments and a note on storybook.
=> [F] Add disabled state for HdLoaderButton

.github/CODEOWNERS
Yes, I made it on GitHub and didn't checkout locally u.u
=> :wrench: Add Lars to CODEOWNERS

src/components/form/HdRadio.vue
Add vertical radio item gap of 16px as align here:
- https://homeday.slack.com/archives/CMQ63UMD0/p1591888123011700
- https://homeday.slack.com/archives/CMQ63UMD0/p1591889438021600
=> [F] radio item gap to 16px

.github/CODEOWNERS, package-lock.json, package.json, src/components/buttons/HdLoaderButton.vue, src/components/buttons/HdRadioButton.vue, src/components/form/HdInput.vue, src/components/form/HdRadio.vue, src/components/gallery/HdGalleryMedia.vue, src/notes/HdIconFillFromClass.md, src/notes/HdLoaderButton.md, src/stories/HdLoaderButton.stories.js, src/stories/icons.stories.js, src/styles/buttons.scss, src/styles/inputs.scss, tests/unit/components/buttons/HdLoaderButton.spec.js, tests/unit/components/form/HdInput.spec.js
- ✨ Browser autofill behavior (#457)
- ✨ validate only non-empty input value (#452)
- ✨ Gitmoji CLI hook (#448)
- ✨ enable html and obj on radio button (#441)
- 💄 radio item gap to 16px (#454)
- 💄 disabled state on loader button (#442)
- 🔧 Add Lars to CODEOWNERS (#455)
- ⬆️🔒 Bump websocket-extensions from 0.1.3 to 0.1.4 (#451)
- 📝 Use homeday-blocks/ instead of homeday/ (#447)
- [B] Remove blurred transition of image slide on Gallery (#435)
=> [Release] v11.1.0

src/components/form/HdInput.vue, src/components/form/HdInputFormatter.vue, src/stories/HdDashedList.stories.js, src/stories/HdInputFormatter.stories.js, src/stories/HdModal.stories.js, tests/unit/components/form/HdInputFormatter.spec.js
🐛 Allow decimal numbers on webkit browsers (#461)
🐛 Validate the original value of HdInputFormatter (#460)
=> [Release] Bugfixes: HdInputFormatter validation + number input

package-lock.json, package.json
=> [T] Version bump: v11.1.1

package-lock.json, package.json
- 🔖 Version bump 11.1.1 (#463)
=> [Release] Version Bump 11.1.1 (#463)

package-lock.json, package.json, src/styles/inputs.scss
🐛 Fix the input label on Firefox (#467)
=> [Release] Fix the input label on Firefox

main.js, src/components/HdLoadingSpinner.vue, src/stories/HdLoadingSpinner.stories.js
Add a HdLoadingSpinner component:
=> [F] Add HdLoadingSpinner component

package-lock.json, package.json, src/components/HdLoadingSpinner.vue, src/components/HdTileSelect.vue, src/components/HdTileSelectEditableItem.vue, src/components/HdTileSelectItem.vue
* 🐛 Fix the mixins import path
* 🔖 Bump to v12.3.1
=> [H] Fix the mixins import path (#497)

README.md, _templates/new/component/main.ejs.t, _templates/new/component/prompt.js, _templates/new/component/story.ejs.t, _templates/new/component/test.ejs.t, _templates/new/component/vue.ejs.t, _templates/new/help/index.ejs.t, _templates/new/service/main.ejs.t, _templates/new/service/prompt.js, _templates/new/service/service.ejs.t, _templates/new/service/test.ejs.t, package-lock.json, package.json
During PEW, I've ported a simple component with @ilyasmez, and we rely in creating scaffolding files that are usually common in every component.
Every new component need:
- A vue/functional component file
- A test file
- A storybook file
- Import the component in `main.js`
My proposal is to add a tool to automate basic file creation in this project.
In this PR I've added [Hygen](https://www.hygen.io/), based in they're website, Hygen is:
> The scalable code generator that saves you time.
Now we can create a new component by running `npm run new component`
=> [F] Add scaffolding tool

README.md, _templates/new/component/main.ejs.t, _templates/new/component/prompt.js, _templates/new/component/story.ejs.t, _templates/new/component/test.ejs.t, _templates/new/component/vue.ejs.t, _templates/new/help/index.ejs.t, _templates/new/service/main.ejs.t, _templates/new/service/prompt.js, _templates/new/service/service.ejs.t, _templates/new/service/test.ejs.t, package-lock.json, package.json, src/components/HdTabsMenu.vue, src/components/gallery/HdGallery.vue, src/components/gallery/HdGalleryCarousel.vue, src/components/gallery/HdGalleryMedia.vue, tests/unit/components/HdTabsMenu.spec.js, tests/unit/components/__snapshots__/HdTabsMenu.spec.js.snap, tests/unit/components/gallery/HDGallery.spec.js, tests/unit/components/gallery/__snapshots__/HDGallery.spec.js.snap
- Add scaffolding tool (#507)
- Redirect link support added to HDGallery component (#490)
- Update HdTabsMenu.vue (#501)
- Bump version to 12.3.2 (#506)
- Bump elliptic from 6.4.1 to 6.5.3 (#491)
=> [Release]  Add scaffolding tool, Support redirect link on HDGallery and HdTabsMenu update

src/services/README.md
https://homeday.atlassian.net/browse/FET-103
=> [doc] Document scroll service

src/components/form/HdInput.vue
Fix for the ticket: https://homeday.atlassian.net/browse/FET-235
=> [B] The error message is not updated when the validation rules of the input change

src/styles/inputs.scss
Ticket: https://homeday.atlassian.net/browse/FET-230
I updated vertical positioning, but also noticed that font sizes were different in figma and updated those as well.
=> [T] Adapt the input label position

src/components/HdDashedList.vue, src/stories/HdDashedList.stories.js, src/stories/mocks/DASHED_LIST_ITEMS.js, tests/unit/components/HdDashedList.spec.js, tests/unit/components/__snapshots__/HdDashedList.spec.js.snap
https://homeday.atlassian.net/browse/DS-100
In this PR:
- Update the HdDashedList component with the design system
- Update HdDashedList component tests
- Update HdDashedList component documentation
=> [T] Update HdDashedList component with the design system

.github/workflows/deploy-pr-to-s3.yml, vue.config.js
This will deploy each PR in an isolated environment, which will make our reviews fast and easy, especially the UI heavy ones, as it will save us the time to checkout to the head branch and install the dependencies etc. It will also allow us to get a QA from the design team before deploying to production, which I think will be so beneficial in this "redesigning" phase.
=> [T] Add the build per PR action

src/styles/main.scss
https://homeday.atlassian.net/browse/DS-122
=> [T] [DS-122] move <hr> styles to blocks

src/components/form/FieldBase.vue, src/components/form/HdCheckbox.vue, src/stories/HdCheckbox.stories.js, tests/unit/components/form/HdCheckbox.spec.js, tests/unit/components/form/__snapshots__/HdCheckbox.spec.js.snap, tests/unit/components/form/__snapshots__/HdDynamicForm.spec.js.snap, tests/unit/components/form/__snapshots__/HdInput.spec.js.snap, tests/unit/components/form/__snapshots__/HdInputPassword.spec.js.snap, tests/unit/components/form/__snapshots__/HdPasswordConfirm.spec.js.snap, tests/unit/components/form/__snapshots__/HdRadio.spec.js.snap, tests/unit/components/form/__snapshots__/HdSelect.spec.js.snap, tests/unit/components/form/__snapshots__/HdSplitInput.spec.js.snap, tests/unit/components/form/__snapshots__/HdTextarea.spec.js.snap, tests/unit/components/tooltip/__snapshots__/HdTooltipped.spec.js.snap
https://homeday.atlassian.net/browse/DS-107
=> [F] Update HdCheckbox component to match the new design

.storybook/preview.js, src/stories/Elevation.stories.js, src/stories/Elevation.vue, src/styles/_elevation.scss, src/styles/main.scss, src/styles/mixins.scss
https://homeday.atlassian.net/browse/DS-91
The shadows are composed of umbra and penumbra, but to give it a more natural look, we also add a soft shadow that comes from the ambient light.
**The anatomy of shadows:**
<a href="https://slideplayer.com/slide/13541327/"><img width="600" src="https://player.slideplayer.com/82/13541327/slides/slide_1.jpg"></a>
=> [F] Elevation

package-lock.json, package.json, src/components/form/FieldBase.vue, src/components/form/HdCheckbox.vue, src/components/form/TextFieldBase.vue, src/stories/HdCheckbox.stories.js, src/styles/main.scss, tests/unit/components/form/HdCheckbox.spec.js, tests/unit/components/form/__snapshots__/HdCheckbox.spec.js.snap, tests/unit/components/form/__snapshots__/HdDynamicForm.spec.js.snap, tests/unit/components/form/__snapshots__/HdInput.spec.js.snap, tests/unit/components/form/__snapshots__/HdInputPassword.spec.js.snap, tests/unit/components/form/__snapshots__/HdPasswordConfirm.spec.js.snap, tests/unit/components/form/__snapshots__/HdRadio.spec.js.snap, tests/unit/components/form/__snapshots__/HdSelect.spec.js.snap, tests/unit/components/form/__snapshots__/HdSplitInput.spec.js.snap, tests/unit/components/form/__snapshots__/HdTextarea.spec.js.snap, tests/unit/components/tooltip/__snapshots__/HdTooltipped.spec.js.snap
💄 add indeterminate state to HdCheckbox (#599)
🎨 (TextFieldBase): the active statement of the input changed (#611)
🐛 (Elevations): make sure to create the elevations from 0 to 10 (#612)
=> [Release] HdCheckbox improvements, fix elevation, fix the input's clearable state

.github/workflows/publish.yml
It will automatically publish our releases to Slack (`#frontend`).
The message will look like the following:
*Secrets already added to the repo*
=> 👷 Notify slack on releases

src/stories/Spacing.stories.js, src/stories/Spacing.vue
https://homeday.atlassian.net/browse/DS-127
=> [T] [DS-127] Add documentation for spacing variables

main.js, src/components/form/HdTileSelect.vue, src/stories/HdTileSelect.stories.js, tests/unit/components/HdTileSelect.spec.js, tests/unit/components/__snapshots__/HdTileSelect.spec.js.snap
I'm moved the component to the `form` directory and added what it needs to be HdForm-compatible.
(You can already notice a repeating pattern, maybe we start using mixins while waiting for the composition API adoption, as repeated code is even worse than mixins :D).
=> [F] Make HdTileSelect HdForm-compatible

src/components/form/HdForm.vue, tests/unit/components/form/HdForm.spec.js
The logic wasn't filtering out the fields to remove.
=> [B] Fix the dynamic removal of HdForm fields

package-lock.json, package.json, src/styles/deprecated_font.scss, src/styles/main.scss
🔇 Reduce the typography warning noise (#637)
🔒 Bump ini from 1.3.5 to 1.3.7 (#633)
=> [Release] Reduce the typography warning noise

src/stories/HdTooltipped.stories.js
Fixed an error on the Tooltipped documents.
**From:**
https://user-images.githubusercontent.com/2879127/105376838-79556500-5c0a-11eb-90a1-8ce18eff0d2e.png
**To:**
https://user-images.githubusercontent.com/2879127/105376833-78243800-5c0a-11eb-82dd-77beba8011a7.png
~~I'm getting an error on the unit tests on local for an unrelated component though.~~
~~So I'm creating the PR to see if it is just me.~~
=> [B] Fixed Tooltipped stories

src/stories/TypographyTextVariants.stories.js
I updated the documentation to display the mixins with the proper parameters instead of the helper classes. I also explained the helper classes in the story content.
=> [B] Fixed Typography Text Variants documentation

.github/workflows/announce-release.yml, .github/workflows/deploy-pr-to-s3.yml, .github/workflows/release.yml
=> 🚀 Fix the release workflow and restructure the others

src/components/HdModal.vue
https://user-images.githubusercontent.com/14016028/119136228-b1957480-ba3f-11eb-8554-63c11b293dc3.MP4
https://user-images.githubusercontent.com/14016028/119136494-020cd200-ba40-11eb-96e3-341f672f68c5.MP4
=> 🐛  Scroll Bugfix of HD Modal

src/components/HdModal.vue
On the current implementation, we have mixed the desired design for **Condensed** and **Wide** modals. You can take a look in the [design reference for Dialogs](https://www.figma.com/file/KdznSjw9btqHEKdgmm2UT4co/Design-System-UI-Patterns?node-id=5621%3A6294).
| Variation | Design reference  | Current implementation | New implementation |
| ------------- | ------------- | ------------- | ------------- |
| **Condensed Desktop** ✅ | <img width="290" alt="condensed--desktop__design" src="https://user-images.githubusercontent.com/7268262/120270063-919b5780-c26e-11eb-93e4-af958621601c.png"> | <img width="525" alt="condensed--desktop__current" src="https://user-images.githubusercontent.com/7268262/120270097-9cee8300-c26e-11eb-9ab1-93db6371ce69.png"> | <img width="526" …
=> 🐛 (hd-modal): fix is-wide implementation to follow DS

.github/workflows/announce-release.yml
You can kill me now or kill me later, doesn't matter 🙈
=> 👷 missing 'v' in version

package-lock.json, src/components/HdModal.vue, src/stories/HdModal.stories.js, tests/unit/components/HdModal.spec.js, tests/unit/components/__snapshots__/HdModal.spec.js.snap
----
Related PR: https://github.com/homeday-de/homeday-blocks/pull/783
Read more: https://github.com/homeday-de/homeday-blocks/pull/783#issuecomment-883400128
Thanks @kuroski
=> 🎨 Improve format of the HdModal in order to override default slots

src/components/form/HdDynamicForm.vue, src/stories/HdDynamicForm.stories.js, tests/unit/components/form/__snapshots__/HdDynamicForm.spec.js.snap
Hey everyone. 
We needed to do an action in MHD Project once the user `@blur` one of the inputs within `HDDynamicForm`. Those changes should be merged with `master` to be able to start the Review & QA process of https://github.com/homeday-de/customer-app/pull/2362. 
* indent spacing fixes
* `blur` support added
=> ✨  `@blur` & `@focus` support for `HDDynamicForm` component

src/components/form/HdTextarea.vue, src/stories/HdTextarea.stories.js, tests/unit/components/form/__snapshots__/HdTextarea.spec.js.snap
Ticket: https://homeday.atlassian.net/browse/VIEW-209
=> ✨ [VIEW-209]: Maxlength support for hdtextarea

.github/CODEOWNERS
- Added some missing frontenders 
- Removed team members that left 😿
=> 🛂 Update CODEOWNERS

.github/CODEOWNERS
Add @hesambayat onto code owners.
=> :passport_control: Update CODEOWNERS

package.json, tsconfig-build.json
Fixing https://github.com/homeday-de/homeday-blocks/actions/runs/2020928444
=> :bug: Fix github actions release CI

package-lock.json, package.json
Upgrade to the latest homeday assets and trigger Storybook build
=> :arrow_up: Bump home-assets from 4.39.7 to 4.41.0

package-lock.json, src/components/form/HdCheckbox.vue, tests/unit/components/form/__snapshots__/HdCheckbox.spec.js.snap
We need to add `role` attribute to the actual input element to be able to reach the checkbox element via the `role` attribute in the customer app. I checked the lighthouse and couldn't see any issue with it, please let me know if you see anything.
* [CL-2798](https://homeday.atlassian.net/browse/CL-2798)
I need this change to be able to query the checkbox element in our test suites of the customer app. We use the testing library and [we can only find elements by their roles](https://testing-library.com/docs/react-testing-library/cheatsheet/#queries). This is the reason why I need to duplicate the role attribute of the HdCheckbox element.
- added role attribute for the checkbox element
=> ✨ New Role Attribute for Checkbox Element 

.github/workflows/ci.yml
Runs check actions on each pull request.
=> :green_heart: Add tests and lint to check on pull request

package.json, src/index.ts
Hi everyone, I am trying to test a pre-release build and make sure it works as expected. Indeed, I expect to see the src folder included in the final build.
=> :wrench: Added src folder to final build

src/index.js
I will merge and directly use it in another PR for the website project.
=> :recycle: Refactor barrel module

src/components/HdPager.vue, src/stories/HdPager.stories.js, tests/unit/components/HdPager.spec.js, tests/unit/components/__snapshots__/HdPager.spec.js.snap
**Task**
https://homeday.atlassian.net/browse/TOFU-4906
**What**
A new layout option for the pager.
Component documentation: https://www.figma.com/file/KdznSjw9btqHEKdgmm2UT4co/Design-System-UI-Patterns?node-id=7%3A100&t=6pwgJeQW0pioLIYG-0
**Why**
This will be used in a new component of the website.
Theresa requested to be reusable, because she will also be using this in other places in the future.
Design: https://www.figma.com/file/0uSB2ZGAOQauErdTfVnZEq/Buyer-Value-component---PA?node-id=187%3A8317&t=spNVZE4rI0yESA4c-0
**Notes**
Layout and animation wise, Theresa already tested and approved.
Now let's see code wise with y'all :)
=> ✨ New pager modifier

src/components/form/HdRange.vue, src/styles/_variables.scss, src/styles/mixins.scss
Same as https://github.com/homeday-de/homeday-blocks/commit/cddd3751b466f6d0d32c278f19c8e3de5ce1d847
We're facing this same issue on the website after the last update.
=> :bug: Fix sass lexical error

src/components/HdBadge.vue, src/components/HdBadgeTypes.ts
=> 🏷️  Convert HdBadge to Typescript

src/components/HdIcon.vue
=> 🏷️ Add typescript to HdIcon

src/components/HdToggle.vue, tests/unit/components/__snapshots__/HdToggle.spec.js.snap
- Add TypeScript to HdToggle
- Allow HdToggle title to be raw HTML for extra customization, like:
=> ✨ Add TypeScript to HdToggle & allow its title to be raw HTML

package-lock.json, package.json
We have new assets to be used.
=> :arrow_up: Update homeday-assets

src/components/form/HdForm.vue, src/components/form/HdInput.vue, src/lang/de.json
- Return true / false to know if all the fields of a form are valid or not (either JS or HTML validations).
- Show a custom error message when  HTML validation fails.
=> :sparkles: Return if all fields are valid inside form

src/components/form/HdInputPhone.vue
https://homeday.atlassian.net/browse/MISO-335
=> :sparkles: Adds option to change hd input phone label
